Project 2 [feat] Styling changes
netlight-johannadagfalk/goclimate pull request #113
Opened 2021-09-13 12:02 UTC by e-ry

Did 8, 9, 10, 11 from the styling changes-list on task 18.2.

Renamed "signUpMotivationText to SignUpIngress to be able to resuse it and and still have legible code.
Title got a new custom_style attribute

Will be cleaned and project-2 pulled and merged before done

2021-09-14 06:35 UTC, teolenn commented
![image](https://user-images.githubusercontent.com/86241480/133206874-6b426eee-4377-4739-83ab-b97cfc05a8fc.png)

I mitt tycke är det lite för mycket space mellan varje bar när jag kör den på localhost. Är det bara jag som tycker det eller vad tycker ni andra?

2021-09-14 06:41 UTC, mabackstr commented on app/assets/main/react_components/footprint_form/Title.jsx
> +    <h2 className={"heading my-4 " + ((!(custom_style === undefined)) ? custom_style : "")} >{text}</h2>
Reagerade på skrivsättet, men kanske bara är jag? Vad känner ni @teolenn @e-ry ? Brukar skriva som förslaget. Obs ej testkört så kanske missförstår syntaxen.

```suggestion
    <h2 className={"heading my-4 " + (custom_style !== undefined ? custom_style : "")} >{text}</h2>
```

2021-09-14 06:42 UTC, mabackstr commented on app/assets/main/react_components/footprint_result/SignUpPreamble.jsx
> + */
Denna tänker jag ej ska vara med om vi tänker clean code-konventionen :)
```suggestion
```

2021-09-14 06:42 UTC, mabackstr commented on tailwind.config.js
> +      lgr: ['1.5rem', theme('lineHeight.8')],
Jag utgår ifrån att det är OK att korrigera config-filen? Eller är det något annat som kan bli tokigt??

2021-09-14 06:49 UTC, mabackstr commented
> ![image](https://user-images.githubusercontent.com/86241480/133206874-6b426eee-4377-4739-83ab-b97cfc05a8fc.png)
> 
> I mitt tycke är det lite för mycket space mellan varje bar när jag kör den på localhost. Är det bara jag som tycker det eller vad tycker ni andra?

Jo men jag håller nog ändå med! Tänker lite mobile first, och en lätt minskning kan nog vara bra. space-y-5 kanske? Eller 4? Bifogar hur det skulle se ut:

space-y-5:
![image](https://user-images.githubusercontent.com/86283836/133208880-209a25fe-bd39-435b-8c46-5f32bcbfb280.png)

space-y-4:
![image](https://user-images.githubusercontent.com/86283836/133208950-03a7c223-8aad-4e0e-aca6-26d42fed7c81.png)

Tror jag föredrar space-y-5!

2021-09-14 06:51 UTC, teolenn requested changes
![image](https://user-images.githubusercontent.com/86241480/133206874-6b426eee-4377-4739-83ab-b97cfc05a8fc.png)

I mitt tycke är det lite för mycket space mellan varje bar, men vad tycker ni andra?

2021-09-14 06:51 UTC, teolenn commented on app/assets/main/react_components/footprint_result/SignUpContainer.jsx
> +                <Title text={sign_up_heading_collective_efficacy} custom_style="text-lgr" />
```suggestion
                <Title 
                    text={sign_up_heading_collective_efficacy} 
                    custom_style="text-lgr" 
                />
```

2021-09-14 06:54 UTC, mabackstr commented
Gillar att det var lite mer space enligt task 11 för emailfältet. Dock väckte det en tanke. Kan vi introducera den ändringen i denna vy också? Bild 1:

![image](https://user-images.githubusercontent.com/86283836/133209556-6dc31195-ff11-47bd-a845-c0d6c9935878.png)

Detta för att nu när man går mellan sidorna för att välja medlemskap och att fylla i mail så blir containern väldigt mycket olika stor, vilket skapar "onödiga glitchar" i containerns storlek. Om man ställer sig och går fram och tillbaka mellan dem förstår man vad jag menar!

Kanske att båda kör med py-2 eller så?

2021-09-14 06:55 UTC, mabackstr requested changes
Enligt kommentarer

2021-09-14 07:11 UTC, teolenn commented
![image](https://user-images.githubusercontent.com/86241480/133211861-ef4b1f14-b0d9-4c35-8a8c-7bc707548b3c.png)
Knappen på mobil. Kanske behöver tänka om lite på den när pilen?

2021-09-14 07:13 UTC, teolenn commented
> Gillar att det var lite mer space enligt task 11 för emailfältet. Dock väckte det en tanke. Kan vi introducera den ändringen i denna vy också? Bild:
> 
> ![image](https://user-images.githubusercontent.com/86283836/133209556-6dc31195-ff11-47bd-a845-c0d6c9935878.png)
> 
> Detta för att nu när man går mellan sidorna för att välja medlemskap och att fylla i mail så blir containern väldigt mycket olika stor, vilket skapar "onödiga glitchar" i containerns storlek. Om man ställer sig och går fram och tillbaka mellan dem förstår man vad jag menar!
> 
> Kanske att båda kör med py-2 eller så?

Ja kanske. Jag tycker inte att det är helt oproportioneligt som det ser ut nu men bra om vi vill aligna med kort-vyn

2021-09-14 07:14 UTC, e-ry commented on app/assets/main/react_components/footprint_form/Title.jsx
> +    <h2 className={"heading my-4 " + ((!(custom_style === undefined)) ? custom_style : "")} >{text}</h2>
Helt rimligt, kommer nog från en "ah juste det är tvärt om!" och inte för att det är bäst

2021-09-14 07:15 UTC, e-ry commented on tailwind.config.js
> +      lgr: ['1.5rem', theme('lineHeight.8')],
Det tror jag inte, de andra storlekarna fungerar fortfarande utan någon ändring! Men kan ju vara värt att testa en extra gång!

2021-09-14 07:42 UTC, teolenn commented
När man gör mindre skärm blir den vita marginalen ovanför progressbar mindre, kanske för liten? Vad tycker ni?
![image](https://user-images.githubusercontent.com/86241480/133216300-1d9897aa-fc16-4648-9c3e-f30b8130bd8c.png)

2021-09-15 06:43 UTC, mabackstr approved these changes

2021-09-15 08:58 UTC, teolenn commented on app/assets/main/react_components/footprint_form/Title.jsx
> +    <h2 className={"heading my-4 " + (custom_style !== undefined ? custom_style : "")} >{text}</h2>
```suggestion
    <h2 className={"heading my-4 " + (custom_style !== undefined ? custom_style : "")}>{text}</h2>
```

2021-09-15 08:59 UTC, teolenn approved these changes

2021-09-15 13:31 UTC, merged