changed style on imported components to avoid using important in tail…
netlight-johannadagfalk/goclimate pull request #117
Opened 2021-09-14 11:36 UTC by netlightebba

…wind config file.

2021-09-14 12:20 UTC, netlight-saraandersson approved these changes

2021-09-14 13:32 UTC, elinaolsson requested changes
The menu seems to work, nice done! However, a small part of the hamburger menu is outside the view in mobile mode and the header is not longer fixed at the top when scrolling.

2021-09-14 13:38 UTC, netlight-johannadagfalk commented
The sidebar is not visible in 100% view, instead it is the problem we had before that you can scroll horizontaly

2021-09-15 09:17 UTC, elinaolsson approved these changes

2021-09-15 09:17 UTC, merged