Project 2 [fix] membership text
netlight-johannadagfalk/goclimate pull request #122
Opened 2021-09-14 13:56 UTC by e-ry

18.2 punkt 14 Membership text from copy

2021-09-15 10:31 UTC, mabackstr commented on config/locales/react/react.sv.yml
> +      multi_desc: "Stöd klimatprojekt motsvarande %{num} gånger ditt klimatavtryck varje månad"
Saknas en newline i EOF
```suggestion
      multi_desc: "Stöd klimatprojekt motsvarande %{num} gånger ditt klimatavtryck varje månad"
      
```

2021-09-15 10:34 UTC, mabackstr requested changes
Såg bra ut! Bara små EOF-newlines som saknades tolkade jag det som!

2021-09-15 10:34 UTC, mabackstr commented on config/locales/react/react.sv.yml
> +      multi_desc: "Stöd klimatprojekt motsvarande %{num} gånger ditt klimatavtryck varje månad"
Saknas en newline i EOF
```suggestion
      multi_desc: "Stöd klimatprojekt motsvarande %{num} gånger ditt klimatavtryck varje månad"
      
```

2021-09-15 10:34 UTC, mabackstr commented on config/locales/react/react.de.yml
> +      multi_desc: "Support climate projects to offset %{num} times your climate footprint each month"
Saknas en newline i EOF
```suggestion
      multi_desc: "Support climate projects to offset %{num} times your climate footprint each month"
      
```

2021-09-15 12:30 UTC, teolenn approved these changes
Good!

2021-09-16 06:01 UTC, mabackstr commented
@e-ry hmm den verkar fortfarande klaga i react.de.yml och react. .yml angående EOF newline?? Men ser konstigt ut

2021-09-16 06:04 UTC, mabackstr commented
> @e-ry hmm den verkar fortfarande klaga i react.de.yml och react.se.yml angående EOF newline?? Men ser konstigt ut

Fattar dock inte varför?

2021-09-16 06:05 UTC, mabackstr commented on config/locales/react/react.sv.yml
> +
@e-ry Hmm undra om det är pga detta? Det behöver inte vara "" runt :) 
```suggestion
    memberships: 
      free_title: Gratis konto
      free_desc: Spara och följ ditt klimatavtryck över tid
      single_title: Kompensera månadsvis
      single_desc: Stöd klimatprojekt motsvarande ditt klimatavtryck varje månad
      multi_title: Kompensera för flera personer
      multi_desc: Stöd klimatprojekt motsvarande %{num} gånger ditt klimatavtryck varje månad
      
```

2021-09-16 06:06 UTC, mabackstr commented on config/locales/react/react.en.yml
> +
Kommentar nedan

```suggestion
    memberships: 
      free_title: Free account
      free_desc: Save and follow your carbon footprint over time
      single_title: Compensate monthly
      single_desc: Support climate projects to offset your climate footprint each month
      multi_title: Compensate multiple times
      multi_desc: Support climate projects to offset %{num} times your climate footprint each month

```

2021-09-16 06:06 UTC, e-ry commented
> > @e-ry hmm den verkar fortfarande klaga i react.de.yml och react.se.yml angående EOF newline?? Men ser konstigt ut
> 
> Fattar dock inte varför?

Inte jag heller, lokalt blir det ingen skillnad om tar bort och lägger till newline så kan inte ens committa ändringen

2021-09-16 06:06 UTC, mabackstr reviewed
Krångel med EOF i två yml-filer --> kanske löses med kommenterade ändringar?

2021-09-16 06:08 UTC, mabackstr commented
> > > @e-ry hmm den verkar fortfarande klaga i react.de.yml och react.se.yml angående EOF newline?? Men ser konstigt ut
> > 
> > 
> > Fattar dock inte varför?
> 
> Inte jag heller, lokalt blir det ingen skillnad om tar bort och lägger till newline så kan inte ens committa ändringen

Får se om att ta bort "" gör någon skillnad! Min prettier hjälpte mig när jag öppnade filerna iallafall

2021-09-16 06:10 UTC, mabackstr approved these changes
Woop happy life!

2021-09-16 06:10 UTC, e-ry commented
> > > > @e-ry hmm den verkar fortfarande klaga i react.de.yml och react.se.yml angående EOF newline?? Men ser konstigt ut
> > > 
> > > 
> > > Fattar dock inte varför?
> > 
> > 
> > Inte jag heller, lokalt blir det ingen skillnad om tar bort och lägger till newline så kan inte ens committa ändringen
> 
> Får se om att ta bort "" gör någon skillnad! Min prettier hjälpte mig när jag öppnade filerna iallafall

Nuså! Tänkte att prettier bara var för js, dumt nog!

2021-09-16 06:10 UTC, merged

2021-09-16 06:11 UTC, teolenn commented
> > > > @e-ry hmm den verkar fortfarande klaga i react.de.yml och react.se.yml angående EOF newline?? Men ser konstigt ut
> > > 
> > > 
> > > Fattar dock inte varför?
> > 
> > 
> > Inte jag heller, lokalt blir det ingen skillnad om tar bort och lägger till newline så kan inte ens committa ändringen
> 
> Får se om att ta bort "" gör någon skillnad! Min prettier hjälpte mig när jag öppnade filerna iallafall

För mig klagade den om jag hade mellanrum på newline. Kan det vara det?

2021-09-16 06:12 UTC, mabackstr commented
> > > > > @e-ry hmm den verkar fortfarande klaga i react.de.yml och react.se.yml angående EOF newline?? Men ser konstigt ut
> > > > 
> > > > 
> > > > Fattar dock inte varför?
> > > 
> > > 
> > > Inte jag heller, lokalt blir det ingen skillnad om tar bort och lägger till newline så kan inte ens committa ändringen
> > 
> > 
> > Får se om att ta bort "" gör någon skillnad! Min prettier hjälpte mig när jag öppnade filerna iallafall
> 
> Nuså! Tänkte att prettier bara var för js, dumt nog!

Ja jag med! Men då lär alltså yml vara med på tåget

2021-09-16 06:12 UTC, mabackstr commented
> > > > > @e-ry hmm den verkar fortfarande klaga i react.de.yml och react.se.yml angående EOF newline?? Men ser konstigt ut
> > > > 
> > > > 
> > > > Fattar dock inte varför?
> > > 
> > > 
> > > Inte jag heller, lokalt blir det ingen skillnad om tar bort och lägger till newline så kan inte ens committa ändringen
> > 
> > 
> > Får se om att ta bort "" gör någon skillnad! Min prettier hjälpte mig när jag öppnade filerna iallafall
> 
> För mig klagade den om jag hade mellanrum på newline. Kan det vara det?

Det kan det absolut vara!