BUGFIX: Added a preventDefault to form to stop it from going to the r…
netlight-johannadagfalk/goclimate pull request #16
Opened 2021-08-09 13:46 UTC by teolenn

Har gjort en lösning som hindrar formuläret att submittas vid enterslag oavsett ätt var i formuläret man är.
Lösningen finns på branchen: p2/bug/submit_on_enter

Om vill ha möjligheten att enterknappen kan ta en vidare i formuläret går det säker att bygga vidare på denna lösning.

Vad tycker ni?

2021-08-09 14:04 UTC, e-ry reviewed
Kalla på onAnswerGiven on enter ist, den BÖR byta till nästa fråga!

2021-08-10 06:22 UTC, mabackstr commented
> Kalla på onAnswerGiven on enter ist, den BÖR byta till nästa fråga!

Gillar denna lösning!

2021-08-10 12:56 UTC, mabackstr requested changes
Se Elisabeths review

2021-08-11 11:16 UTC, teolenn commented
> Jag tycker onKeyDown ska heta onKeyPress men jag godkänner så får du göra som du vill!

Håller med! Ändrade nu till onKeyPress

2021-08-11 15:03 UTC, mabackstr requested changes
Ser bra ut kodlogikmässigt, men har litet önskemål för att vi ska vara konsekventa!

2021-08-11 15:03 UTC, mabackstr commented on app/assets/main/react_components/footprint_form/OptionNumerical.jsx
> +        <input autoFocus type="text" min="0" pattern="[0-9]+[.,]?[0-9]*" max="2147483647" size="7" className="flex-1" value={value} onKeyPress={handleKeyDown}
Tänker att vi ska vara konsekventa med att antingen deklarera funktioner vid själva taggen, eller utanför (som du har nu). Så du kanske kan välja något av alternativen! Ger ena alternativet här.

```suggestion
        <input autoFocus type="text" min="0" pattern="[0-9]+[.,]?[0-9]*" max="2147483647" size="7" className="flex-1" value={value} 
              onKeyPress={(e) => {
                if (event.key === 'Enter') {
                    setValue("");
                    /* .replace() makes sure that trailing commas (, or .) are removed */
                    onAnswerGiven(value.replace(/[,.]\s*$/, ""));
                }
              }} 
```

2021-08-12 06:40 UTC, teolenn commented on app/assets/main/react_components/footprint_form/OptionNumerical.jsx
> +        <input autoFocus type="text" min="0" pattern="[0-9]+[.,]?[0-9]*" max="2147483647" size="7" className="flex-1" value={value} onKeyPress={handleKeyDown}
Fixed!

2021-08-12 06:41 UTC, mabackstr approved these changes

2021-08-12 06:42 UTC, e-ry commented on app/assets/main/react_components/footprint_form/OptionNumerical.jsx
> +        <input autoFocus type="text" min="0" pattern="[0-9]+[.,]?[0-9]*" max="2147483647" size="7" className="flex-1" value={value} onKeyPress={handleKeyDown}
Jag har googlat nu, och hittar ingenting om best practice. Jag har känslan av att man definierar korta funktioner inuti och om de är långa utanför, den här är någonstans i mitten så man kan nog göra som man vill. Men jag har definierat mest utanför så just nu är vi inte konsekventa ändå!

2021-08-12 07:10 UTC, merged