Project 2 [feat] Responsive membership boxes
netlight-johannadagfalk/goclimate pull request #171
Opened 2021-09-23 11:40 UTC by e-ry

2021-09-24 06:27 UTC, teolenn commented
![image](https://user-images.githubusercontent.com/86241480/134628326-5a0f3da5-20ca-4620-8e31-037f978ffd01.png)

Membership-boxarna försvinner vid bredd  768

2021-09-24 07:04 UTC, teolenn reviewed
Mest förslag i denna 😊

2021-09-24 09:15 UTC, mabackstr requested changes
Småändringsförslag dokumenterade som kommentarer! Övergripande kommentar för att simplifiera: stryka props:en "mobile", "title" och "sellingPoints" som skickas in till MembershipAlternativeV2-komponenterna i MembershipsListV2.jsx, sen som följd stryka propsen "mobile", "title" och "sellingPoints" som skickas in till MembershipAlternativeV2Desktop- och MembershipAlternativeV2Mobile-komponenterna i MembershipAlternativeV2.jsx och istället hämta ut den informationen som skickades via props:en via useTexts:

MembershipAlternativeV2Desktop.jsx:
```
const MembershipAlternativeV2Desktop = ({
  selectedMembership,
  setSelectedMembership,
  type,
  multipleOffsets,
  setMultipleOffsets,
  grantedReferralCode,
  price,
  style,
}) => {

/* 'type' kan nämligen användas som en "dynamisk nyckel" för att peka på rätt ställen i useTexts! */
  const {
    reactContentText: {
      memberships_v2: {
        desktop: { [type]: { title, selling_points } },
      },
    },
  } = useTexts();
....



MembershipAlternativeV2Mobile.jsx:

const MembershipAlternativeV2Mobile = ({
  selectedMembership,
  setSelectedMembership,
  type,
  multipleOffsets,
  setMultipleOffsets,
  grantedReferralCode,
  price,
  style,
}) => {
  const {
    reactContentText: {
      memberships_v2: {
        mobile: {
          [type]: { title, selling_point},
        }
      },
    }
  } = useTexts();
....

2021-09-24 12:20 UTC, e-ry commented on app/assets/shared/components/react_responsive.css
> +  .show-on-desktop {
Jag tänkte också det, men den är ju både för mobile och tablet, så ville signalera det men då blev det så fult!

2021-09-27 06:57 UTC, mabackstr requested changes
Två små stackars props som råkat smita med bara! Sen good to go.

2021-09-27 06:57 UTC, mabackstr commented on app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/components/membership_alternative/MembershipAlternativeV2.jsx
> +  mobile,
```suggestion
```

2021-09-27 06:57 UTC, mabackstr commented on app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/sign_up_page/components/membership_page/components/memberships_list/components/membership_alternative/MembershipAlternativeV2.jsx
> +          mobile={mobile}
```suggestion
```

2021-09-27 07:15 UTC, teolenn approved these changes

2021-09-27 07:16 UTC, mabackstr approved these changes

2021-09-27 07:19 UTC, merged