Project 2 [fix] Styling fixes, general
netlight-johannadagfalk/goclimate pull request #187
Opened 2021-09-27 09:47 UTC by e-ry

Centrera ingresser
Vänsterjustera texter under content
Ta bort välj medlemskap
Ökade avståndet till progress bar på sign up (tror jag)
Rubriken för projekten ändrad

-har inte ändrat storlekar på rubrik, ligger i en annnan pr tror jag

2021-09-27 12:35 UTC, teolenn approved these changes

2021-09-28 06:31 UTC, mabackstr requested changes
Några grejer jag såg som jag spontant tror skulle vara bra att kirra!

2021-09-28 06:31 UTC, mabackstr commented on app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/result_page/ResultPage.jsx
> +    }, 2);
I och med att denna används på två ställen kanske den skulle kunna flytta ut till en hjälpfunktions-fil?

Sedan hade det även varit super om den görs om till en arrow function istället!

2021-09-28 06:32 UTC, e-ry commented on app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/result_page/ResultPage.jsx
> +    }, 2);
Den är ett WIP som tillhör en annan branch! Jag håller på att försöka flytta committen

2021-09-28 06:49 UTC, mabackstr commented
Väntar med review till efter conflict är löst så alla margin-ändringar ser OK ut med dessa styling-ändringar!

2021-09-28 11:32 UTC, mabackstr requested changes
Bara liten ändring för att få med min ändring från förra styling-PR:en!

2021-09-28 11:32 UTC, mabackstr commented on app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/result_page/components/category_section/CategoryPage.jsx
> +      <Title custom_style="text-lgr" text={title} />
Detta blev fel vid pull project-2, det är customStyle som används. Så den ändringen skedde i min förra styling-PR :) 
```suggestion
      <Title customStyle="text-lgr" text={title} />
```

2021-09-28 12:39 UTC, e-ry commented on app/assets/main/react_components/routes/lifestyle_footprints/footprint_form_container/components/footprint_form/components/result_page/components/category_section/CategoryPage.jsx
> +      <Title custom_style="text-lgr" text={title} />
Sjukt namngett av mig!

2021-09-28 13:04 UTC, mabackstr approved these changes
Grymt!

2021-09-28 13:05 UTC, merged