Feat/1 checklist
netlight-johannadagfalk/goclimate pull request #5
Opened 2021-06-30 12:12 UTC by netlight-johannadagfalk

Regarding tests:

bin/guard
bin/rspec
bin/rubocop

--> gives the same results as for dev branch

Same console error as for dev exists: POST https://api-iam.intercom.io/messenger/web/ping 403

Earlier commits are from junk-branch

2021-06-30 12:41 UTC, netlightebba requested changes
Good work! I have some thoughts or suggestions, see my comments :D

2021-06-30 12:41 UTC, netlightebba commented on app/assets/main/react_components/Button.jsx
> +      return (
Avoid adding extra space, check git Working Tree to see these changes and go through and revert accidental/unnecessary spaces and indents.

2021-06-30 12:41 UTC, netlightebba commented on app/assets/main/react_components/Button.jsx
> +        <button
Avoid adding extra space, check git Working Tree to see these changes and go through and revert accidental/unnecessary spaces and indents.

2021-06-30 12:41 UTC, netlightebba commented on app/assets/main/react_components/User/ActionFeature.jsx
> +    const ifChecked = (id) => {
Maybe name this function _onCheck_? Similar to a button with "onClick".

2021-06-30 12:41 UTC, netlightebba commented on app/assets/main/react_components/User/ActionFeature.jsx
> +                        <Checklist challenges={challenges} ifChecked={ifChecked} isOnlyAccepted={true} />
Maybe rename prop "ifChecked" on checklist to onCheck? Similar to a button with "onClick".

2021-07-01 06:33 UTC, netlightebba approved these changes

2021-07-01 06:44 UTC, netlight-saraandersson approved these changes

2021-07-01 07:54 UTC, merged