P2/feat/911 continue to payment button
netlight-johannadagfalk/goclimate pull request #53
Opened 2021-08-24 09:17 UTC by teolenn

Har gjort ett skal för "Continue to payment! knappen. Saknar submit-funktionalitet pga att det kommer implementeras när vi går till nästa sida i "resultat"-formuläret.

2021-08-24 11:17 UTC, mabackstr requested changes
Finns det ett behov av att introducera en ny komponent för knappen om den endast består av en AnswerButton? Eller kan AnswerButton-komponenten användas istället i SignUpContainer?

2021-08-25 11:39 UTC, teolenn commented
> Finns det ett behov av att introducera en ny komponent för knappen om den endast består av en AnswerButton? Eller kan AnswerButton-komponenten användas istället i SignUpContainer?

Tänkte mest att det skulle vara tydligt att det inte var en AnswerButton, men anser att vi istället kan i ett refactoreringsskede döpa om AnswerButton till ett mer generellt namn. Men tar bort PaymentButton i denna branch.

2021-08-25 11:41 UTC, teolenn commented
Även 9.16 (Pris) hamnade i denna branch

2021-08-25 12:23 UTC, e-ry approved these changes

2021-08-25 12:23 UTC, e-ry commented on app/views/devise/registrations/new.html.erb
>        commonText: YAML.load_file('config/locales/' + I18n.locale[0..-1] + '.yml')[I18n.locale[0..-1]].to_json,
Kan inte months tas ur commonText? Om jag inte kollar fel är det samma fil!

2021-08-25 12:23 UTC, e-ry commented on app/assets/main/react_components/footprint_result/SignUpContainer.jsx
>                                  />
```suggestion
                                    membershipText={signUpText.membership}
                                    selectedMembership={selectedMembership} 
                                    setSelectedMembership={setSelectedMembership}
                                />
```

2021-08-25 12:23 UTC, e-ry commented on app/assets/main/react_components/footprint_result/PriceText.jsx
> +            <span><span>{extractPrice(price, currency)}</span>/{months.one}</span>
```suggestion
            <span>
                   <span>{extractPrice(price, currency)}</span>
                   /{months.one}
            </span>
```

2021-08-25 12:23 UTC, e-ry commented on app/assets/main/react_components/footprint_result/PriceText.jsx
> +            <span><span>{extractPrice(price, currency)}</span>/{months.one}</span>
Spelar inte så stor roll exakt hur det ser ut, men tyckte det var mycket spans på en gång!

2021-08-25 12:23 UTC, e-ry commented on app/assets/main/react_components/footprint_result/PriceText.jsx
> +    var price = (price.subunit_amount/100)
Förstår att du inte skrivit detta men GUD vad det tog mig tid att förstå att det står sub-unit och inte bara "subunit"

2021-08-30 06:19 UTC, mabackstr commented on app/assets/main/react_components/footprint_result/SelectorMultipleTimes.jsx
> +const SelectorMultipleTimes = ({multipleOffsets, setMultipleOffsets}) => {
```suggestion
const SelectorMultipleTimes = ({ multipleOffsets, setMultipleOffsets }) => {
```

2021-08-30 06:19 UTC, mabackstr approved these changes

2021-08-30 08:50 UTC, merged