Project 2 [feat]: Result inside form
netlight-johannadagfalk/goclimate pull request #62
Opened 2021-08-26 10:37 UTC by mabackstr

### Footprint calculation result is now included on the form page.

**Tasks: 10.1, 10.2**

When the submit to BE is performed, the BE no longer returns a redirect, but the footprint result.

When the fetch result is received, the "result" state is set to the resulting footprint object that was received.

When the result has been received, the form goes to the next step in the form, i.e. does not show the flight question but moves on to the result category.

The result is stored in SessionStorage, so that if the user goes back in the form but does not change any answer, the fetch call is not performed unnecessarily.

The category state has been removed due to its nature not fitting well with content that is not question-based. What is shown in the FootprintForm is now dependent on the "question"index (i.e. currentIndex).

In FootprintForm, JSX is now divided into two different pages: QuestionPage and ResultPage. While the user is in the calculator-based view of FootprintForm (answering questions), QuestionPage is used. When the user views result-related information, ResultPage is used. currentIndex (previously known as questionIndex) is now a state. With this, a state for the category is not needed and simplified the construction of the result page.

2021-08-30 06:48 UTC, teolenn commented on app/assets/main/react_components/footprint_form/FootprintForm.jsx
> +        response.json().then(calculatedFootprint => {
Hur funkar det här?
Som jag förstår det är calculatedFootprint responsobjektet från servern, är det då det färdigberäknade objektet?

2021-08-30 14:20 UTC, teolenn requested changes
Snyggt! Bara några pyttesmå grejer

2021-08-30 14:20 UTC, teolenn commented on app/assets/main/react_components/footprint_form/FootprintForm.jsx
> +
Kan överväga att ge dessa funktioner en liten kodkommentar även om de är korta

2021-08-30 14:20 UTC, teolenn commented on app/assets/main/react_components/footprint_form/QuestionPage.jsx
> +            />
```suggestion
                <OptionList 
                    onAnswerGiven={(givenAnswer) => onAnswerGiven(givenAnswer)} 
                    options={options.options}
                    selectedKey={selectedKey} 
                />
```

2021-08-30 14:20 UTC, teolenn commented on app/assets/main/react_components/footprint_form/QuestionPage.jsx
> +            />
```suggestion
                <OptionNumerical 
                    onAnswerGiven={(givenAnswer) => onAnswerGiven(givenAnswer)} 
                    option={options} 
                    onNumericalInput={onNumericalInput}
                    savedValue={savedValue} 
                />
```

2021-08-30 14:46 UTC, mabackstr commented on app/assets/main/react_components/footprint_form/FootprintForm.jsx
> +
Hmm jag tänkte att namnen på funktionerna var nog beskrivande, men det kanske jag bör lägga till! @e-ry som tredje part får du säga vad du tycker!

2021-08-31 07:57 UTC, teolenn approved these changes

2021-08-31 11:41 UTC, e-ry approved these changes
Har inte kollat noga på allt, men jag tänker att när vi refaktorerar tillsammans kommer det sista lösa sig!

2021-08-31 11:41 UTC, e-ry commented on app/assets/main/react_components/footprint_form/Container.jsx
> +
Gillar den här lösningen

2021-08-31 11:41 UTC, e-ry commented on app/assets/main/react_components/footprint_form/QuestionPage.jsx
> +export default QuestionPage
```suggestion
export default QuestionPage

```

Git tycker det ska va newline här, men bara i denna fil?? Mkt skumt

2021-08-31 12:13 UTC, merged