Project 2 [FEATURE]: Submit on enter at referral code
netlight-johannadagfalk/goclimate pull request #80
Opened 2021-09-02 07:04 UTC by teolenn

2021-09-02 07:07 UTC, mabackstr requested changes
Se kommentar

2021-09-02 07:07 UTC, mabackstr commented on app/assets/main/react_components/footprint_result/ReferralCode.jsx
> +                                onKeyPress = {(e) => onKeyPress(e)}
Snyggt med enkel lösning! Tänkte bara om vi ska hålla oss till våra mini-konventioner, då ska koden ligga deklarerad här i taggen :)

2021-09-02 13:21 UTC, e-ry commented on app/assets/main/react_components/footprint_result/ReferralCode.jsx
> +                                onKeyPress = {(e) => onKeyPress(e)}
Rimlig input! Jag approvear eftersom jag inte har fler ändringar att lägga till

2021-09-03 12:57 UTC, teolenn commented on app/assets/main/react_components/footprint_result/ReferralCode.jsx
> +                                onKeyPress = {(e) => onKeyPress(e)}
👍

2021-09-03 13:19 UTC, mabackstr approved these changes

2021-09-03 13:19 UTC, merged