Project 2 [fix] Remove irrelevant links when price is free
netlight-johannadagfalk/goclimate pull request #82
Opened 2021-09-02 08:06 UTC by e-ry

2021-09-02 13:48 UTC, mabackstr requested changes
Kanske bara olika skolor men några kommentarer rörande condition-skrivsätt! Sedan några små log-meddelanden som ska rensas bort :)

2021-09-02 13:48 UTC, mabackstr commented on app/assets/main/react_components/footprint_result/MembershipSelector.jsx
> +            { !(selectedMembership === "free") &&
Kanske bara är olika "skolor", men vad jag sett brukar man skriva enligt förslag nedan. Då behöver man bara kolla "på ett ställe" för att förstå vilket condition som evalueras. Tankar?
```suggestion
            { selectedMembership !== "free" &&
```

2021-09-02 13:48 UTC, mabackstr commented on app/assets/main/react_components/footprint_result/Payment.jsx
> +    console.log(selectedMembership === "free")
```suggestion
```

2021-09-02 13:48 UTC, mabackstr commented on app/assets/main/react_components/footprint_result/Payment.jsx
> +        }
Samma förslag som tidigare kommentar och indenteringsfix bara!
```suggestion
        { selectedMembership !== "free" &&
        <>
            <label className="block font-semibold mt-3">{commonStrings.credit_or_debit_card}</label>
            <CardElement className="py-3 w-full input mb-1 StripeElement StripeElement--empty"/>
            <i className="fas fa-lock" aria-hidden="true"></i>
            <span className="ml-1">Secured by Stripe</span>
        </>
        }
```

2021-09-02 13:48 UTC, mabackstr commented on app/assets/main/react_components/footprint_result/PriceText.jsx
> +                { !(selectedMembership === "free") &&
Likt tidigare. 
```suggestion
                { selectedMembership !== "free" &&
```

2021-09-03 13:41 UTC, teolenn commented on app/assets/main/react_components/footprint_result/Payment.jsx
> +        </>
```suggestion
            <>
              <label className="block font-semibold mt-3">{commonStrings.credit_or_debit_card}</label>
              <CardElement className="py-3 w-full input mb-1 StripeElement StripeElement--empty"/>
              <i className="fas fa-lock" aria-hidden="true"></i>
              <span className="ml-1">Secured by Stripe</span>
            </>
```
Så kanske?

2021-09-03 13:42 UTC, teolenn requested changes
En en liten indenteringsgrej bara

2021-09-03 14:11 UTC, teolenn approved these changes

2021-09-03 14:11 UTC, mabackstr approved these changes

2021-09-03 14:13 UTC, merged